"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),http=require("node:http"),{once}=require("node:events"),{WebSocket}=require("ws");
const E=require("./richman-engine"),D=require("./richman-data"),{attachRichman}=require("./richman-server");
const game=(n=3)=>E.createGame(Array.from({length:n},(_,i)=>"Player "+i),{},()=>.45);
const act=(g,a,id=g.current)=>E.apply(g,id,a,()=>.45);
function seed(n){return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
test("board, starting assets and card privacy",()=>{const g=game();assert.equal(D.tiles.length,36);assert.equal(new Set(D.tiles.map(t=>`${t.x},${t.y}`)).size,36);assert.equal(Object.keys(D.gods).length,12);assert.equal(Object.keys(D.cards).length,27);assert.equal(E.assets(g,g.players[0]),50000);const s=E.snapshot(g,0);assert.equal(s.players[0].cards.length,5);assert.equal(s.players[1].cards,null);assert.equal(s.players[1].shares,null);assert.equal("aiTurn"in s.players[0],false);});
test("invalid or out-of-turn actions are atomic",()=>{const g=game();for(const a of [{type:"bank",amount:-1},{type:"roll",dice:5},{type:"buy"},{type:"lottery",number:99},{type:"stock",stock:0,quantity:-10,side:"buy",quote:40},{type:"card",card:"equal"}]){const before=structuredClone(g);assert.throws(()=>act(g,a));assert.deepEqual(g,before);}assert.throws(()=>act(g,{type:"roll"},1));});
test("bank stop preserves remaining movement",()=>{const g=game();g.gods=[];g.players[0].pos=15;g.players[0].controlled=3;act(g,{type:"roll"});assert.equal(g.phase,"bank");assert.equal(g.remaining,2);assert.equal(g.players[0].pos,16);act(g,{type:"bank",amount:1000,direction:"withdraw"});assert.equal(g.players[0].cash,26000);act(g,{type:"done"});assert.equal(g.players[0].pos,18);assert.equal(g.remaining,0);assert.equal(g.phase,"property");});
test("Sundays skip the bank and market",()=>{const g=game();g.day=4;g.gods=[];g.players[0].pos=15;g.players[0].controlled=3;act(g,{type:"roll"});assert.equal(g.players[0].pos,18);assert.equal(g.phase,"property");assert.throws(()=>act(g,{type:"stock",stock:0,quantity:1,side:"buy",quote:40}));});
test("land buying, five levels, and combined street rent",()=>{const g=game(),t=g.tiles[1];g.players[0].pos=1;g.phase="property";act(g,{type:"buy"});assert.equal(t.owner,-1,"atomic actions replace objects");assert.equal(g.tiles[1].owner,0);for(let i=0;i<5;i++){g.phase="property";act(g,{type:"upgrade"});}g.phase="property";assert.throws(()=>act(g,{type:"upgrade"}));assert.equal(g.tiles[1].level,5);g.tiles[2].owner=0;assert.equal(E.rent(g,g.tiles[1]),Math.round(g.tiles[1].price*.08*16+g.tiles[2].price*.08));});
test("Fortune grants free land and double upgrades; Misfortune charges failed investment",()=>{const g=game();g.players[0].pos=1;g.phase="property";E.attachGod(g,g.players[0],"luck",()=>.45);act(g,{type:"buy"});assert.equal(g.players[0].cash,25000);g.phase="property";act(g,{type:"upgrade"});assert.equal(g.tiles[1].level,2);E.attachGod(g,g.players[0],"bad",()=>.45);const cash=g.players[0].cash;g.phase="property";act(g,{type:"upgrade"});assert.equal(g.tiles[1].level,2);assert.ok(g.players[0].cash<cash);});
test("Rent waiver and Amnesty consume exactly one matching card",()=>{const g=game();g.players[1].cards=["free","pardon"];E.pay(g,1,5000,0,true);assert.equal(g.players[1].cash,25000);assert.deepEqual(g.players[1].cards,["pardon"]);g.players[0].cards=["jail"];act(g,{type:"card",card:"jail",target:1});assert.equal(g.players[1].restUntil,0);assert.deepEqual(g.players[1].cards,[]);});
test("Guardian, Angel and Devil apply along traversed plots",()=>{for(const[type,expectedOwner,level]of[["land",0,2],["angel",1,3],["devil",1,1]]){const g=game();g.gods=[];g.tiles[1].owner=1;g.tiles[1].level=2;g.players[0].god={type,until:8};g.players[0].controlled=1;act(g,{type:"roll"});assert.equal(g.tiles[1].owner,expectedOwner);assert.equal(g.tiles[1].level,level);}});
test("expiry exchanges paired deities",()=>{const g=game();g.gods=[];g.players[0].god={type:"angel",until:2};E.nextDay(g,()=>.45);assert.equal(g.players[0].god,null);assert.equal(g.gods[0].type,"devil");});
test("all 27 cards have valid effects or documented automatic use",()=>{for(const key of Object.keys(D.cards)){const g=game();g.players[0].cards=[key];g.players[1].cards=["free"];g.players[0].pos=1;g.tiles[1].owner=key==="buy"?1:0;g.tiles[2].owner=1;g.tiles[1].level=2;g.tiles[2].level=3;g.players[0].god={type:"bad",until:8};const targets=E.cardTargets(g,0,key);if(D.cards[key][4]==="auto"){assert.deepEqual(targets,[]);continue;}assert.ok(targets.length,key);act(g,{type:"card",card:key,target:targets[0]});assert.ok(!g.players[0].cards.includes(key),key);}});
test("stock ownership, quotes and deposits validated for off-turn trading",()=>{const g=game();act(g,{type:"stock",stock:0,side:"buy",quantity:100,quote:40},1);assert.equal(g.players[1].shares[0],100);assert.equal(g.players[1].deposit,21000);for(const a of [{side:"sell",quantity:101,quote:40},{side:"buy",quantity:10000,quote:40},{side:"sell",quantity:1,quote:41}])assert.throws(()=>act(g,{type:"stock",stock:0,...a},1));act(g,{type:"stock",stock:0,side:"sell",quantity:100,quote:40},1);assert.equal(g.players[1].deposit,25000);});
test("Bull and Bear cards last three market days, can cancel, prices stay within 10%",()=>{const g=game();g.players[0].cards=["red","black"];act(g,{type:"card",card:"red",target:0});assert.equal(g.stocks[0].forceDays,3);E.nextDay(g,()=>.5);assert.equal(g.stocks[0].price,44);assert.equal(g.stocks[0].limit,1);assert.throws(()=>act(g,{type:"stock",stock:0,side:"buy",quantity:1,quote:44}));act(g,{type:"card",card:"black",target:0});assert.equal(g.stocks[0].forceDays,0);const h=game();h.players[0].cards=["red"];act(h,{type:"card",card:"red",target:0});E.nextDay(h,()=>.5);E.nextDay(h,()=>.5);assert.equal(h.stocks[0].forceDays,1);E.nextDay(h,()=>.5);assert.equal(h.stocks[0].forceDays,1);E.nextDay(h,()=>.5);assert.equal(h.stocks[0].forceDays,0);for(let i=0;i<300;i++){const old=h.stocks.map(s=>s.price);E.nextDay(h,seed(i));h.stocks.forEach((s,j)=>assert.ok(s.price<=old[j]*1.1+.001&&s.price>=old[j]*.9-.001));}});
test("lottery exclusive tickets, cash cost, winner and rollover",()=>{const g=game();g.phase="lottery";act(g,{type:"lottery",number:1});assert.equal(g.lottery.pool,21000);assert.equal(g.players[0].cash,24000);assert.throws(()=>act(g,{type:"lottery",number:1}));for(let i=2;i<=5;i++)act(g,{type:"lottery",number:i});assert.throws(()=>act(g,{type:"lottery",number:6}));g.day=14;E.nextDay(g,()=>0);assert.equal(g.lottery.draw.number,1);assert.equal(g.lottery.draw.winner,0);assert.equal(g.players[0].cash,45000);assert.deepEqual(g.lottery.tickets,{});assert.equal(g.lottery.pool,20000);g.day=45;g.lottery.pool=25000;E.nextDay(g,()=>0);assert.equal(g.lottery.pool,25000);assert.equal(g.lottery.draw.winner,-1);});
test("month-end deposits and 15th dividends",()=>{const g=game();g.day=14;g.players[0].shares[0]=100;E.nextDay(g,()=>.5);assert.equal(g.players[0].deposit,25120);g.day=30;E.nextDay(g,()=>.5);assert.equal(g.players[0].deposit,27632);});
test("liquidation uses deposit, shares and half-value property before bankruptcy",()=>{const g=game();g.players[0].cash=100;g.players[0].deposit=200;g.players[0].shares[0]=5;g.tiles[1].owner=0;E.pay(g,0,1700,1);assert.equal(g.players[0].deposit,0);assert.equal(g.players[0].shares[0],0);assert.equal(g.tiles[1].owner,-1);assert.equal(g.players[0].cash,250);assert.equal(g.players[0].out,false);E.pay(g,0,1000,1);assert.equal(g.players[0].out,true);assert.equal(g.players[0].cash,0);});
test("bankruptcy on landing advances current player, last solvent wins",()=>{const g=game();g.gods=[];g.players[0].cash=1;g.players[0].deposit=0;g.players[0].cards=[];g.players[0].controlled=1;g.tiles[1].owner=1;g.tiles[1].level=5;act(g,{type:"roll"});assert.equal(g.players[0].out,true);assert.equal(g.current,1);assert.equal(g.phase,"roll");E.pay(g,2,999999,1);assert.equal(g.phase,"over");assert.deepEqual(g.winners,[1]);});
test("day limit settles the highest net worth, including ties",()=>{const g=game();g.limitDays=30;g.day=30;g.players[0].cash+=100;g.players[1].cash+=100;E.nextDay(g,()=>.5);assert.equal(g.phase,"over");assert.deepEqual(g.winners,[0,1]);});
test("bots finish seeded 2-6 player games without illegal moves or negative balances",()=>{for(let seedId=1;seedId<=16;seedId++){const rng=seed(seedId),g=E.createGame(Array.from({length:2+seedId%5},(_,i)=>"Bot "+i),{days:30},rng);let n=0;while(g.phase!=="over"&&n++<2500){const id=g.current;E.apply(g,id,E.botAction(g,id,["easy","normal","hard"][seedId%3],rng),rng);for(const p of g.players){assert.ok(Number.isFinite(p.cash)&&p.cash>=0);assert.ok(p.deposit>=0);assert.ok(p.shares.every(n=>Number.isInteger(n)&&n>=0));assert.ok(p.cards.length<=D.MAX_CARDS);}}assert.equal(g.phase,"over",`seed ${seedId}, phase ${g.phase}`);assert.ok(g.winners.length);}});
test("multiplayer privacy, host authority, revision checks and reconnect",async()=>{
  const server=http.createServer(),r=attachRichman(server,{botDelay:30});server.on("upgrade",r.upgrade);server.listen(0,"127.0.0.1");await once(server,"listening");const url=`ws://127.0.0.1:${server.address().port}/richman-ws`,clients=[];
  async function client(token){const ws=new WebSocket(url),messages=[];clients.push(ws);ws.on("message",raw=>messages.push(JSON.parse(raw)));await once(ws,"open");const c={ws,messages,send:data=>ws.send(JSON.stringify(data)),wait:async fn=>{const until=Date.now()+4000;while(Date.now()<until){const index=messages.findIndex(fn);if(index>=0)return messages.splice(index,1)[0];await new Promise(resolve=>setTimeout(resolve,10));}throw Error("Message timeout");}};c.send({type:"hello",token});c.token=(await c.wait(m=>m.type==="welcome")).token;return c;}
  try{
    const a=await client(),b=await client();a.send({type:"create",name:"Connie",players:3,funds:50000,days:30,difficulty:"hard"});const lobby=await a.wait(m=>m.type==="state");b.send({type:"join",name:"Colin",code:lobby.code});await b.wait(m=>m.type==="state");
    b.send({type:"bots",fill:true});assert.match((await b.wait(m=>m.type==="error")).message,/Host only/);
    a.send({type:"bots",fill:true});b.send({type:"ready",ready:true});await a.wait(m=>m.type==="state"&&m.seats.every(p=>p?.ready));a.send({type:"start"});const sa=await a.wait(m=>m.game),sb=await b.wait(m=>m.game);assert.equal(sa.game.players[1].cards,null);assert.equal(sb.game.players[0].cards,null);assert.ok(sa.game.players[0].cards.length);assert.equal(sa.seats[2].bot,true);
    b.send({type:"action",revision:0,action:{type:"roll"}});assert.match((await b.wait(m=>m.type==="error")).message,/Not your turn/);
    a.send({type:"action",revision:999,action:{type:"roll"}});assert.match((await a.wait(m=>m.type==="error")).message,/Board changed/);
    a.send({type:"chat",text:"Hello 晴湾"});assert.equal((await b.wait(m=>m.chat?.length)).chat[0].text,"Hello 晴湾");
    a.send({type:"leave"});await a.wait(m=>m.type==="left");const left=await b.wait(m=>m.type==="state"&&m.seats[0].connected===false);assert.equal(left.host,1);
    a.send({type:"join",code:lobby.code,name:"Connie"});const back=await a.wait(m=>m.type==="state"&&m.game&&m.you===0&&m.seats[0].connected);assert.equal(back.seats[0].auto,false);
    const oldAvatar=back.seats[2].avatar;const a2=await client(a.token);const rejoined=await a2.wait(m=>m.game);assert.equal(rejoined.you,0);assert.deepEqual(rejoined.seats[2].avatar,oldAvatar);
    const room=r.rooms.get(lobby.code);room.game.phase="over";room.game.winners=[1];b.send({type:"start"});const restart=await b.wait(m=>m.game?.revision===0&&m.game?.phase==="roll");assert.equal(restart.host,1);
  }finally{clients.forEach(ws=>ws.terminate());server.close();server.emit("close");}
});
