"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),http=require("node:http"),{once}=require("node:events");
const{attachRichman}=require("./richman-server"),D=require("./richman-data");
let playwright;try{playwright=require("playwright");}catch{playwright=require(path.resolve(path.dirname(process.execPath),"../node_modules/playwright"));}
const server=http.createServer((req,res)=>{const file=path.join(__dirname,new URL(req.url,"http://localhost").pathname);if(!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end();return;}res.setHeader("Content-Type",({".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css",".svg":"image/svg+xml"})[path.extname(file)]||"text/plain");fs.createReadStream(file).pipe(res);});
const rich=attachRichman(server);server.on("upgrade",rich.upgrade);
(async()=>{let browser;
  try{
    server.listen(0,"127.0.0.1");await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`;
    browser=await playwright.chromium.launch({executablePath:process.env.CHROME_PATH||"C:/Program Files/Google/Chrome/Application/chrome.exe",headless:true});fs.mkdirSync("test-results",{recursive:true});const errors=[];
    async function client(name){const ctx=await browser.newContext({viewport:{width:1440,height:1000}});await ctx.addInitScript(()=>{const Native=WebSocket;window.WebSocket=class extends Native{constructor(...args){super(...args);window.testSocket=this;this.addEventListener("message",e=>{const m=JSON.parse(e.data);if(m.type==="state")window.testState=m;});}};});const page=await ctx.newPage();page.on("pageerror",e=>errors.push(e.message));await page.goto(base+"/richman.html");await page.getByText("已连接 / Connected",{exact:true}).waitFor();await page.locator("#playerName").fill(name);return{ctx,page};}
    const a=await client("Connie"),b=await client("William");
    for(const width of[320,390,1440]){await a.page.setViewportSize({width,height:900});assert.equal(await a.page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await a.page.screenshot({path:`test-results/richman-setup-${width}.png`,fullPage:true});}
    await a.page.setViewportSize({width:1440,height:1000});await a.page.locator('[data-modal="rules"]').click();await a.page.locator('[data-rule-tab="gods"]').click();assert.equal(await a.page.locator(".rule-figure").count(),12);await a.page.locator('[data-rule-tab="cards"]').click();assert.equal(await a.page.locator(".rule-figure").count(),27);assert.equal(await a.page.locator("i[data-lucide]").count(),0,"Every icon must resolve");await a.page.locator("#closeDialog").click();
    await a.page.locator("#createBtn").click();await a.page.locator("#roomCode").waitFor();const code=await a.page.locator("#roomCode").textContent();await b.page.locator("#roomInput").fill(code);await b.page.locator("#joinForm button").click();await b.page.locator("[data-ready]").click();await a.page.locator("[data-add-bots]").click();await a.page.waitForFunction(()=>window.testState.seats.every(p=>p?.ready));await a.page.locator("[data-room-start]").click();await a.page.waitForFunction(()=>window.testState.game);
    assert.equal(await a.page.locator(".richman-map [data-tile]").count(),36);assert.equal(await a.page.locator(".rich-player").count(),4);
    assert.equal(await a.page.locator('.rich-player[data-player="0"] .presence-dot').evaluate(e=>getComputedStyle(e).backgroundColor),"rgb(36, 151, 107)");
    await a.page.locator('[data-card="dice"]').first().click();await a.page.locator('[data-target="1"]').click();await a.page.locator('[data-use-card="dice"]').click();await a.page.waitForFunction(()=>window.testState.game.players[0].controlled===1);await a.page.locator('[data-act="roll"]').click();await a.page.locator('[data-act="buy"]:not([disabled])').waitFor();await a.page.locator('[data-act="buy"]').click();await a.page.waitForFunction(()=>window.testState.game.tiles[1].owner===0);await a.page.locator('[data-act="done"]').click();await b.page.waitForFunction(()=>window.testState.game.current===1);
    await a.page.locator('[data-modal="stocks"]').click();await a.page.locator('[data-order="0"]').fill("11");await a.page.locator('[data-stock-buy="0"]').click();await a.page.waitForFunction(()=>window.testState.game.players[0].shares[0]===11);assert.equal(await a.page.locator('[data-order="0"]').inputValue(),"11");
    await a.page.setViewportSize({width:390,height:844});assert.equal(await a.page.locator("#richDialog").evaluate(e=>e.scrollWidth>e.clientWidth),false);await a.page.screenshot({path:"test-results/richman-stocks-mobile.png",fullPage:true});await a.page.locator("#closeDialog").click();
    await a.page.locator("#board").scrollIntoViewIfNeeded();const mapBox=await a.page.locator("#board").boundingBox(),cdp=await a.ctx.newCDPSession(a.page),cy=mapBox.y+mapBox.height/2;
    await cdp.send("Input.dispatchTouchEvent",{type:"touchStart",touchPoints:[{x:140,y:cy,id:1},{x:240,y:cy,id:2}]});
    await cdp.send("Input.dispatchTouchEvent",{type:"touchMove",touchPoints:[{x:90,y:cy,id:1},{x:290,y:cy,id:2}]});
    await cdp.send("Input.dispatchTouchEvent",{type:"touchEnd",touchPoints:[]});
    await a.page.waitForFunction(()=>document.querySelector("#board").classList.contains("zoomed"));assert.ok(await a.page.locator("#mapCanvas").evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).a>1.5));
    assert.equal(await a.page.locator("#richDialog").getAttribute("open"),null);await a.page.screenshot({path:"test-results/richman-pinch-mobile.png",fullPage:true});await a.page.waitForTimeout(500);await a.page.locator("#resetMap").click();assert.equal(await a.page.locator("#board").evaluate(e=>e.classList.contains("zoomed")),false);
    await a.page.locator("#chatText").fill("晴湾见！ See you in Sunny Bay");await a.page.locator("#chatForm button").click();await b.page.locator(".chat-bubble").waitFor();assert.match(await b.page.locator(".chat-bubble").textContent(),/Sunny Bay/);
    const room=rich.rooms.get(code);
    async function fixture(phase,pos){room.game.phase=phase;room.game.current=0;room.game.players[0].pos=pos;room.game.lastMove=null;room.game.revision++;await a.page.evaluate(()=>window.testSocket.send(JSON.stringify({type:"chat",text:"Ready"})));await a.page.waitForFunction(({phase,pos})=>window.testState.game.phase===phase&&window.testState.game.players[0].pos===pos,{phase,pos});}
    await fixture("bank",16);await a.page.locator('#actions [data-modal="bank"]').click();await a.page.locator("#bankAmount").fill("1234");const cash=room.game.players[0].cash;await a.page.locator('[data-bank="withdraw"]').click();await a.page.waitForFunction(c=>window.testState.game.players[0].cash===c+1234,cash);await a.page.locator("#closeDialog").click();
    await fixture("lottery",24);await a.page.locator('#actions [data-modal="lottery"]').click();await a.page.locator('[data-ticket="17"]').click();await a.page.waitForFunction(()=>window.testState.game.lottery.tickets[17]===0);assert.equal(await a.page.locator('[data-ticket="17"]').isDisabled(),true);await a.page.screenshot({path:"test-results/richman-lottery-mobile.png",fullPage:true});await a.page.locator("#closeDialog").click();
    room.game.players[0].cards=Object.keys(D.cards).slice(0,12);room.game.players[0].god={type:"wealth",until:8};room.game.players[1].god={type:"devil",until:8};for(const t of room.game.tiles)if(t.type==="land"&&t.id%3!==0){t.owner=t.id%4;t.level=t.id%6;}
    await fixture("roll",5);
    for(const width of[320,390,1440]){await a.page.setViewportSize({width,height:width===1440?1050:844});assert.equal(await a.page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await a.page.screenshot({path:`test-results/richman-game-${width}.png`,fullPage:true});}
    await a.page.locator('[data-player="0"] [data-edit-avatar]').click();await a.page.locator("#avatarEmoji").fill("☀️");await a.page.locator("#avatarSave").click();await b.page.waitForFunction(()=>window.testState.seats[0].avatar?.kind==="emoji");
    await a.page.reload();await a.page.waitForFunction(()=>window.testState?.game&&window.testState.you===0);assert.equal(await a.page.locator('[data-player="0"] .avatar-emoji').textContent(),"☀️");
    await b.ctx.close();await a.page.waitForFunction(()=>window.testState.seats[1].connected===false);assert.equal(await a.page.locator('[data-player="1"] .presence-dot').evaluate(e=>getComputedStyle(e).backgroundColor),"rgb(146, 153, 157)");
    room.game.phase="over";room.game.winners=[0];room.game.reason="Test finish";room.game.revision++;await a.page.evaluate(()=>window.testSocket.send(JSON.stringify({type:"chat",text:"GG"})));await a.page.getByText("Connie 胜利！",{exact:false}).waitFor();
    await a.ctx.close();assert.deepEqual(errors,[]);console.log("PASS: Richman multiplayer, mobile/desktop, pinch zoom, 36 tiles, cards, buy land, stocks, bank, lottery, rules, avatars, chat, presence, reconnect and winner");
  }finally{await browser?.close();server.close();server.emit("close");}
})().catch(e=>{console.error(e);process.exitCode=1;});
